accounts/urls.py
from django.contrib.auth.views import logout
from django.urls import path

from accounts.views import send_login_email, login

urlpatterns = [
    path('send_login_email', send_login_email, name="send_login_email"),
    path('login', login, name="login"),
    path('logout', logout, dict(next_page="/"), name="logout"),
]

lists/urls.py
from django.urls import path

from lists.views import view_list, new_list, my_lists

urlpatterns = [
    path('new', new_list, name="new_list"),
    path('<int:list_id>/', view_list, name="view_list"),
    path('users/<str:email>/', my_lists, name="my_lists"),
]

project/urls.py
from django.urls import path, include
from django.views.generic import RedirectView

from lists.views import home_page

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    path('', home_page, name="home"),
    path('lists/', include("lists.urls")),
    path('accounts/', include("accounts.urls")),
]

accounts/models.py
import uuid

# Create your models here.
from django.contrib import auth
from django.db.models import Model, EmailField, CharField

auth.signals.user_logged_in.disconnect(auth.models.update_last_login)


class User(Model):
    email = EmailField(primary_key=True)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True


class Token(Model):
    email = EmailField()
    uid = CharField(max_length=40, default=uuid.uuid4)

lists/models.py
from django.db import models
from django.db.models import Model, TextField
from django.urls import reverse

from project import settings


class List(Model):
    # owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=None)

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    @property
    def name(self):
        return self.item_set.first().text


class Item(Model):
    text = TextField(default="")
    list = models.ForeignKey(List, on_delete=models.CASCADE, default=None)

lists/forms.py
from django.forms import ModelForm, TextInput

from lists.models import Item

EMPTY_ITEM_ERROR = 'You can`t have an empty list item'
PLACE_HOLDER = "Ввведите текст задачи"


class ItemForm(ModelForm):
    def save(self, for_list):
        self.instance.list = for_list
        return super().save()

    class Meta:
        model = Item
        fields = ("text",)

        widgets = {
            "text": TextInput(
                attrs={
                    "placeholder": PLACE_HOLDER,
                    "class": "form-control input-lg"
                }
            )
        }

        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }


class NewListForm:
    ...

accounts/views.py
import sys

from django.contrib import messages, auth
from django.core.mail import send_mail
from django.shortcuts import redirect

from accounts.models import Token


def send_login_email(request):
    email = request.POST["email"]
    # print(type(send_mail))
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri('login?token=' + str(token.uid))
    send_mail(
        'You login link for List To-Do',
        f'Use this link to log in: \n\n {url}',
        'noreplay@superlists',
        [email]
    )
    messages.success(request, "Проверьте свою почту, мы отправили Вам ссылку, которую можно использовать для входа на сайт")
    return redirect("/")


def login(request):
    print('login view', file=sys.stderr)
    uid = request.GET.get('token')
    user = auth.authenticate(uid=uid)
    if user:
        auth.login(request, user)
    return redirect("/")

lists/views.py
from django.shortcuts import render, redirect

from accounts.models import User
from lists.forms import ItemForm, NewListForm
from lists.models import Item, List
from lists.settings import templateListPage, templateHomePage


def home_page(request):
    # print(ItemForm().as_p())
    return render(request, templateHomePage, dict(form=ItemForm()))


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ItemForm()

    if request.method == "POST":
        form = ItemForm(data=request.POST)
        if form.is_valid():
            form.save(for_list=list_)
            return redirect(list_)
    return render(request, templateListPage, dict(list=list_, form=form))


def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List()
        if request.user.is_authenticated:
            list_.owner = request.user
        list_.save()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, "home.html", dict(form=form))

def new_list2(request):
    form = NewListForm(data=request.POST)
    list_ = form.save(owner=request.user)
    return redirect(str(list_.get_absolute_url()))
    # return redirect(list_)


def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, "my_lists.html", dict(owner=owner))

lists/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To-Do lists</title>

    <!-- Bootstrap -->
    <link href={% static "bootstrap/css/bootstrap.css" %} rel="stylesheet">
    <link href={% static "base.css" %} rel="stylesheet">

</head>
<body>
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Superlists</a>
            {% if user.email %}
                <ul class="nav navbar-nav navbar-left">
                    <li><a href="{% url 'my_lists' user.email %}">My lists</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="navbar-text">Logged in as {{ user.email }}</li>
                    <li><a href="{% url 'logout' %}">Log out</a></li>
                </ul>
            {% else %}
                <form class="navbar-form navbar-right" method="post" action="{% url 'send_login_email' %}">
                    <span>Enter email to Log in:</span>
                    <input class="form-control" name="email" type="text"/>
                    {% csrf_token %}
                </form>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        <div class="row">
            <div class="col-md-8">
                {% for message in messages %}
                    {% if message.level_tag == 'success' %}
                        <div class="alert alert-success">{{ message }}</div>
                    {% else %}
                        <div class="alert alert-warning">{{ message }}</div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
            <div class="text-center">
                <h1>{% block header_text %}{% endblock %}</h1>
                {% block list_form %}
                    <form method="post" action="{% block form_action %}{% endblock %}">
                        {{ form.text }}
                        {% csrf_token %}
                        {% if form.errors %}
                            <div class="form-group has-error">
                                <div class="help-block">{{ form.text.errors }}</div>
                            </div>
                        {% endif %}
                    </form>
                {% endblock %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block table %}
            {% endblock %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block extra_content %}
            {% endblock %}
        </div>
    </div>
</div>
<script src="/static/jquery-3.3.1.js"></script>
</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url "new_list" %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your a To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
            <tr>
                <td>{{ forloop.counter }}: {{ item.text }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}My lists{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
    <h2>{{ owner.email }}'s  lists</h2>
    <ul>
     {% for list in owner.list_set.all %}
         <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a> </li>
    {% endfor %}
    </ul>
{% endblock %}